#!/bin/bash

# Normal setup
#   different cores for each port.

name=`uname -n`
if [ $name == "keithw-W2600CR" ]; then
./app/pktgen -c 1f -n 3 --proc-type auto --socket-mem 256,256 --file-prefix pg -b 0000:03:00.0 -b 0000:03:00.1 -- -p 0x00c -P -m "[1:3].0, [2:4].1" -f black-yellow.theme
fi

if [ $name == "keithw-S5520HC" ]; then
./app/pktgen -c 1f -n 3 --proc-type auto --socket-mem 256,256 --file-prefix pg -b 0000:01:00.0 -b 0000:01:00.1 -- -p 0x03 -P -m "[1:3].0, [2:4].1" 
fi
