#!/bin/sh

# Normal setup
#   different cores for each port.
./app/build/pktgen -c 1f -n 3 --proc-type auto --socket-mem 256,256 --file-prefix pg -b 0000:03:00.0 -b 0000:03:00.1 -- -p 0x00c -P -m "[1:3].0, [2:4].1" 
