#!/bin/sh

# Normal setup
#   different cores for each port.
#./app/build/pktgen -c 1ff -n 3 --proc-type auto --socket-mem 256,256 -- -p 0x3c -P -m "[1:3].0, [2:4].1, [5:7].2, [6:8].3" -s 0:pcap/large.pcap
#./app/build/pktgen -c 1f -n 3 --proc-type auto --socket-mem 128,128 --file-prefix pg -- -p 0x3c -P -m "[1:3].0, [2:4].1, [5:7].2, [6:8].3" -s 0:pcap/test1.pcap -s 1:pcap/large.pcap
#./app/build/pktgen -c 1f -n 3 --proc-type auto --socket-mem 128,128 --file-prefix pg -- -p 0x3c -P -m "[1:3].0, [2:4].1, [5:7].2, [6:8].3" -s 0:pcap/test1.pcap -s 1:pcap/large.pcap
./app/build/pktgen -c 1f -n 3 --proc-type auto --socket-mem 128,128 --file-prefix pg -- -p 0x30 -P -m "[1:3].0, [2:4].1"
#./app/build/pktgen -c e -n 3 --proc-type auto --socket-mem 128,128 --file-prefix pg -- -p 0x14 -P -m "2.0, 3.1" -f test/set_seq.cmd
#./app/build/pktgen -c e -n 3 --proc-type auto --socket-mem 128,128 -- -p 0x14 -P -m "2.0, 3.1"
#./app/build/pktgen -c 1ff -n 3 --proc-type auto --socket-mem 256,256 -- -p 0x3c -P -m "[1:3].0, [2:4].1, [5:7].2, [6:8].3"
#./app/build/pktgen -c 1f -n 3 --proc-type auto --socket-mem 128,128 -- -p 0x30 -P -m "[1:3].0, [2:4].1"
