#!/bin/bash

dd=wr-all-pktgen-$1-`date +"%Y%m%d"`.tgz

if [ "x"$1 == "x" ]; then
	echo "Must give the a version number e.g. 2.0.10"
	exit
fi

cat <<-EOF | sed -e '/^#.*/d' > file_list
# DPDK changes to 1.3.0-183
	app/test/test.[ch]
	app/test/test_ring.c
	config/defconfig_x86_64-wr-linuxapp-gcc
	lib/librte_eal/common/include/rte_eal.h
	lib/librte_eal/common/include/rte_hexdump.h
	lib/librte_eal/common/Makefile
	lib/librte_eal/common/eal_common_hexdump.c
	lib/librte_eal/linuxapp/eal/Makefile
	lib/librte_eal/linuxapp/eal/eal.c
	lib/librte_hash/rte_hash.h
	lib/librte_mbuf/rte_mbuf.c
	lib/Makefile
	mk/rte.app.mk
	mk/rte.subdir.mk
# WR lib
	lib/libwr_common/Makefile
	lib/libwr_common/*.[ch]
	lib/libwr_lua/doc
	lib/libwr_lua/COPYRIGHT
	lib/libwr_lua/Makefile
	lib/libwr_lua/README
	lib/libwr_lua/*.[ch]
	lib/libwr_mcos/*.[ch] 
	lib/libwr_mcos/Makefile 
	lib/libwr_mcos/README.mcos 
	lib/libwr_msg/Makefile
	lib/libwr_msg/rte_msg.[ch]
	lib/libwr_scrn/Makefile
	lib/libwr_scrn/rte_scrn.[ch]
# Pktgen files
	wr-examples/pktgen/app/*.[ch] 
	wr-examples/pktgen/app/Makefile 
	wr-examples/pktgen/test
	wr-examples/pktgen/Makefile 
	wr-examples/pktgen/Pktgen.lua
	wr-examples/pktgen/README.pktgen 
	wr-examples/pktgen/clr 
	wr-examples/pktgen/doit 
	wr-examples/pktgen/setup 
	wr-examples/pktgen/*.pdf
# mcos
	wr-examples/mcos_demo
	wr-examples/mcos_ipc
EOF

tar cvzf $dd `cat file_list`
rm file_list
