#!/bin/bash

dd=wr-all-pktgen-$1-`date +"%Y%m%d"`.tgz

if [ "x"$1 == "x" ]; then
	echo "Must give the a version number e.g. 2.0.10"
	exit
else
	cd ..
	find dpdk-pktgen -follow -type f | sed -e '/\.git*/d' | sed -e '/\.DS/d' | sed -e '/\.pcap/d' | sed -e '/kswitch/d' | sed -e '/inp-cfg/d' >file_list
	tar cvzf $dd `cat file_list`
	rm file_list
fi
